// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Observability.DbContext;

#nullable disable

namespace Observability.Migrations
{
    [DbContext(typeof(WeatherDbContext))]
    partial class WeatherDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Observability.Domain.Weather", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Temperature")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Weather");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dda00da3-9379-497b-bd2f-bc2b479f561e"),
                            City = "New York",
                            Temperature = 25
                        },
                        new
                        {
                            Id = new Guid("e38eedaf-092c-4376-a606-45ea14b41aab"),
                            City = "Los Angeles",
                            Temperature = 30
                        },
                        new
                        {
                            Id = new Guid("0ee64386-08eb-42b6-8b56-5e07fb009ec0"),
                            City = "Chicago",
                            Temperature = 20
                        },
                        new
                        {
                            Id = new Guid("47b4fd08-495d-4b88-9c15-d49e29d7d07a"),
                            City = "Houston",
                            Temperature = 15
                        },
                        new
                        {
                            Id = new Guid("ab59ab63-3568-4b7a-a6a1-ca84cba2f677"),
                            City = "Phoenix",
                            Temperature = 10
                        },
                        new
                        {
                            Id = new Guid("aef610f8-9364-4a63-8374-7598df451027"),
                            City = "Philadelphia",
                            Temperature = 5
                        },
                        new
                        {
                            Id = new Guid("93719b20-bafd-4243-9cc7-8c4cc86046f2"),
                            City = "San Antonio",
                            Temperature = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
